### ISSUE TITLE
Congratulations on your acceptance into EMNLP

### ISSUE THREAD

**Issue by HappyGu0524** [LZY-the-boys/MIRACLE#1]
Hi, congratulations on your acceptance into EMNLP!
I find that we share similar thought of constructing latent spaces for control.
Would you mind cite our work in your related work?
> A Distributional Lens for Multi-Aspect Controllable Text Generation. EMNLP 2022
> Controllable Text Generation via Probability Density Estimation in the Latent Space. ACL 2023

**Comment by LZY-the-boys** [comment]
Certainly! Your insights and contributions are undoubtedly significant. Due to the paper page limits, I've already committed to citing specific works such as personalized-dialogue and EBM that closely align with our domain. However, I would be very honored to include your valuable papers in our GitHub repo and in our forthcoming researchs. Thank you for your understanding!
